Crash report: 
Exception: Input is already a datetime object, expected a string.
Traceback: 
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/crash_reports.py", line 33, in run_with_crash_writing
    function(*args, **kwargs)
    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/./scheduler.py", line 914, in main
    scheduleDf, blocks, schedule, candidateDict, configDict = createSchedule(TMO, sunsetUTC, sunriseUTC,
                                                              ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                                            blacklist, whitelist,
                                                                            ^^^^^^^^^^^^^^^^^^^^^
                                                                            excludedTimeRanges,
                                                                            ^^^^^^^^^^^^^^^^^^^
                                                                            candidateDbPath,
                                                                            ^^^^^^^^^^^^^^^^
                                                                            temperature=temperature)
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/./scheduler.py", line 724, in createSchedule
    timeConstraintDict = {c.CandidateName: TimeConstraint(Time(stringToTime(c.StartObservability)),
                                                               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yesod/Desktop/Code/Arizona/alora/maestro/scheduleLib/genUtils.py", line 376, in stringToTime
    raise TypeError("Input is already a datetime object, expected a string.")
